# Generated by Django 5.0.3 on 2025-06-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messages_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="receiver",
            new_name="recipient",
        ),
    ]
